server:
  port: 8080

spring:
  application:
    name: keystone-backend
  
  # Default Profile uses H2 in PostgreSQL compatibility mode
  datasource:
    url: jdbc:h2:mem:keystonedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Keystone Application Specific Properties
keystone:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION:86400000} # 24 hours
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}

logging:
  level:
    com.keystone: INFO
    org.springframework.security: INFO
